language: python
python:
  - "3.7"
install:
  - pip install -r backend/requirements.txt
deploy:
  provider: heroku
  on:
    branch: development
  api_key:
    secure: 2501472b-422d-42f3-8a84-d8450f544fa9
script:
  - echo "Success"
