language: python
python:
- '3.7'
install:
- pip install -r backend/requirements.txt
script:
- npm install -g @vue/cli
- cd backend
- rm /templates/index.html
- rm -r /static
- cd ..
- cd frontend
- npm run build
- cp dist/index.html ../backend/templates
- cp -r dist/static ../backend
- cd backend
before_deploy:
- heroku
branches:
  only:
  - main
  - travis
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: 3DO/BH6wrEW8PuTyhVUmOH3XtgzFM05BycpMcfXgsaf5Am6wG9lWTnAZreE/Rdh32Hk5wTXCeZbrknFjahE/hMWHpfH+os7VmmxPZVuFGxNh3759aNDBLUXQrU4VoNN83iasozLM2fEWseO1wp+1ixdVKvG7X4u+IicH/eMnsPzuuJW7Epz3xZLu3ye/DpzN0Z5/fZwe/7HSmMu+jWIYtM/mDWpJOWgF82jdFGsTlvzizucujhv0todwcUn0soz2XYcL+ruGvoSqn5G8Ec9D/rAIpFU41fEBXyLHoWEDTzWh1zXFJiiXQug7hJNU2uZSWG1SsBwbmv+LZQIKhIXVWwQioqr5K45HT5g6sNqEjk+dAPllDvDneBpEhZFlziG/O64EWprqcAptX7fKNSWBepqW+3vyh8vZIVWZIeJx9Smxp5wnwC+n4W/vgXl5djG/LcBxuEKsm36zxpYlGgLeLUc9WtQ4z2FZvk1fTjhCc7sZLFr3mDEhoKBCUpFzVRTjZrRQDxmv0K7PiaD+Iy8kjhdBJ1qgQSBqKqmACnP/GX5QsF0qXOPB9ndoDz67/RZ095eiwK7xy1tC9LY0h8rZrJ3KwmOp30BDOZrhdotNHwIgLRZNDp0WZo5EO4hovb1FLKOu63COZma4dHK/25vTjF59c7CBowzMbMWDwGAOkzU=
  app:
    main: bike__aRent
    travis: bike-a-rent
