language: python
python:
- '3.7'
install:
- pip install -r backend/requirements.txt
before_deploy:
  - cd backend
deploy:
  provider: heroku
  on:
    branch: travis_testing
  api_key:
    secure: fznj/dypfdhTOr0LLwzeMhp3rbbbkhXGUUQuzzKn6xGR1h4LIWhfUNYveixHLpPXc0VtMlAB1N/Dwc36OTETCOAwjA5psWoD4tL5EwgZejBZigic8kt1rzma9hxv30jtlwc62p0lQkQUDSWAfv8k7+hKs0ARbFxgme9wwba0JgR4mEOfDkCULuQVzYkF5xe4sA4UFXZmy8o0jXGgXvyRwj8xCjkX6EBkwYLgp8uYAXRokvY/CJz7tMnaf9IATDyXejHE3s86H41o8/E018v/Hbs6QW0zYcnka6GIxvTRBi0Q/r7XcEfrqQ4iXugVYx78FfOuVvkCl34UKYXepAUX0ALe90fdk8XKbsQB0OIIOmmaeURGVoIPma4ehf8cgLMwN29kWH7fxdzn3dzMgh/PyZ0d0miZMGqtwkBIE/aOrAo5rAQ+gCdYj2StaBZ/z48h6xFMPMs+a4/vRJ6zUcrzDgPzAjPJ1GIvpyN1hPF1D3YEYf7KhEZiucEGiQG98Sk+OC2Es8IduuVDHTO0gNXfiSIK2CUyVuK/88FhNX1+L5gYLdX/nkUMIsvITcSHAlUfTw8bSE8JC8EaxKkxURCeiukG1rrn5E+RPSXC7Ca0kckKdh20EazNdOjrhjJb5FhEDP1m9vYtcQo+20WHACn1vY1N8YPt2vOJa0JGXH5Mi1c=
script:
- echo "Success"
