language: python
python:
- '3.7'
install:
- pip install -r backend/requirements.txt
deploy:
  provider: heroku
  on:
    branch: development
  api_key:
    secure: tDHifPAmby27Fg4zSmHzjXEPeOLvncACBJpNF7O+pORXRsgULt7i9y6BPYN1f8WTphcsL9y3wMsqGgMGohCtMgb3Anccd5I/Sgwt9IguqZWw0PobJojJdcfz6XYEZJGsKKz035nwmJREo/4V3mFTHwaM2akdmR2I9b04L8dSp4bR7ow1A4KelrhgCroT287Jvb4OQ+Ez55JcVyw61b5S8VXByHhplCOwX/iJS2HB5Lfw6cN+3dAOoFF1jRsrXUZ9h44jrU5PMPRWvAuQGuBTlcBN53xbOiiY//XBhdDqrTlYbMgJBWJ0bSNA8+TGNvgnIWGAxaBXlBzmoCHqFUh9tdej5ObfVyVj/2VcOXMllJF1LKBtF1vAXFgMyp2IDbcDuJby5vNa/OCkd3E0uBhrkdWDA+GMDs1kBBIJhub3sO1RwkLMSHdmkwgeQhqniIKP6Zk8OE4pA6W3kwo/McO0LTyVZJ53yhx/nZHhIV8jUeGvr11omIJZUHwIDcV3/HoKTakMmfQIKctezUupDNjg1FbvRHxwB2PrbG5zh/P4p5mPXMVMzm8t4lrMBvn2XxY5IL868IDEzIpC/PxCGYOnF5TJJpnEPtJM6gvDiHZELqZrs8upFUBOU1GMbwMgQgWHHhxoJl1YFvwipyj3VE0scGsao5CeCDe6O6mIOMx8hiE=
script:
- echo "Success"
