language: python
python:
  - "3.7"
install:
  - pip install -r backend/requirements.txt
deploy:
  provider: heroku
  on:
    branch: development
  api_key:
    secure: "kdsfklsmfakfmafmadslvsdfasdf"
script:
  - echo "Success"
